[package]

name = "seax"
version = "0.0.1"
authors = ["Hawk Weisman <hawk@meteorcodelabs.com>"]
description = "SECD virtual machine for interpreting programs in FP languages"

[dependencies]
docopt = "*"
regex = "*"
rustc-serialize = "*"

[dependencies.seax_svm]
path = "seax_svm"

[dependencies.seax_scheme]
path = "seax_scheme"