[package]

name = "seax"
version = "0.0.1"
authors = ["Hawk Weisman <hawk@meteorcodelabs.com>"]
description = "SECD virtual machine for interpreting programs in FP languages"

[dependencies]
docopt = "0.6.30"
rustc-serialize = "0.2.8"

[dependencies.seax-svm]
path = "seax-svm"

[dependencies.seax-scheme]
path = "seax-scheme"